import { writable } from "svelte/store";

export const productList = writable([
  {
    id: 1,
    name: "Светер SHARK",
    price: "1990",
    isHeart: false,
    img: "/person-slider.png",
    cart: false,
  },
  {
    id: 2,
    name: "Штани BAGGY",
    price: "1230",
    isHeart: false,
    img: "/person-slider1.png",
    cart: false,
  },
  {
    id: 3,
    name: "Кофта Knitted",
    price: "1240",
    isHeart: false,
    img: "/person-slider2.png",
    cart: false,
  },
  {
    id: 4,
    name: "Светер SHARK2",
    price: "2300",
    isHeart: false,
    img: "/person-slider.png",
    cart: false,
  },
  {
    id: 5,
    name: "Кофта Knitted2",
    price: "1450",
    isHeart: false,
    img: "/person-slider2.png",
    cart: false,
  },
  {
    id: 6,
    name: "Майка Shorty",
    price: "450",
    isHeart: false,
    img: "/person-slider1.png",
    cart: false,
  },
  {
    id: 7,
    name: "Светер SHARK2",
    price: "980",
    isHeart: false,
    img: "/person-slider.png",
    cart: false,
  },
  {
    id: 8,
    name: "Светере Cola",
    price: "230",
    isHeart: false,
    img: "/person-slider2.png",
    cart: false,
  },
]);
